### ISSUE TITLE
Update casbin & actix-web dependency

### ISSUE THREAD

**Issue by hackerchai** [casbin-rs/examples#34]
Please update casbin to v2 and actix-web to v3.

**Comment by hackerchai** [comment]
@PsiACE  Could help with this issue.

**Comment by PsiACE** [comment]
Ok i will fix it at night.

**Comment by PsiACE** [comment]
Done: https://github.com/casbin-rs/examples/commit/f5a71846e0b7e5d82e51acc45f7611161f521d29
