### ISSUE TITLE
Fix the ntex CI error

### ISSUE THREAD

**Issue by hackerchai** [casbin-rs/examples#35]
See the latest [CI Result](https://github.com/casbin-rs/examples/runs/1174623490).

**Comment by hackerchai** [comment]
@PsiACE Can you help with this issue?

**Comment by PsiACE** [comment]
Ok i will fix it at night

**Comment by hackerchai** [comment]
@PsiACE Is the error caused by the ntex itself? So we should wait for the ntex's fixing release.

**Comment by PsiACE** [comment]
Currently, this is indeed an error caused by the upstream project ntex.

**Comment by hackerchai** [comment]
Seems it is worked.
